### ISSUE TITLE
Certificate for bayrationality.com is invalid

### ISSUE THREAD

**Issue by jkopczyn** [skycrossman/bayrationality#3]
HTTPS for the landing site fails:

> Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for www.bayrationality.com. The certificate is only valid for the following names: *.github.io, github.io, githubusercontent.com, www.github.com, *.github.com, *.githubusercontent.com, github.com
 
> Error code: [SSL_ERROR_BAD_CERT_DOMAIN](about:certerror?e=nssBadCert&u=https%3A//www.bayrationality.com/&c=UTF-8&d=%20#certificateErrorDebugInformation)

And then in the certificate itself, as stated, it has

> Common Name    *.github.io

> Subject Alt Names
> DNS Name    *.github.io
> DNS Name    github.io
> DNS Name    githubusercontent.com
> DNS Name    www.github.com
> DNS Name    *.github.com
> DNS Name    *.githubusercontent.com
> DNS Name    github.com

**Comment by jkopczyn** [comment]
I am not understanding how the `CNAME` file we have works, but all the answers I've seen elsewhere say that this has to happen at the DNS provider level, which only @skycrossman has.

**Comment by jkopczyn** [comment]
can't work out anything to be done from the repo side, https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site didn't suggest anything that was out of step

Did try something from https://medium.com/@xiang_zhou/how-to-add-custom-domain-to-your-jekyll-blog-provided-that-you-built-your-site-using-github-6e1c8bf20afe and switched `production_url` (in place of `url`), but that did not help, feel free to revert.

**Comment by skycrossman** [comment]
DNS settings changed, SSL cert should be good now. Summary: Squarespace DNS settings expect the CNAME data to point at skycrossman.github.io, not bayrationality.com, and then the redirection happens on Github's side. This is not ideal longterm (it's plausible I might set up a different github page and want a different domain for that!) at which point I think the move is to spin out bayrationality as an organization. Still, it works for now.
